# 第2版への序文 {.unnumbered}

"Rではじめるデータサイエンス"第2版へようこそ！
第1版から大きく作り直しました。も
はや有益でないと考えた材料を削除、第1版に含めていたら良かったのにと思った材料を追加、そして、ベストプラクティスの変化を反映して文章とコードを総じてアップデートしました。
また、とても嬉しいことに新しい共著者を迎えることができました。M
ine Çetinkaya-Rundelです。彼
女は著名なデータサイエンス教育者であり、Posit (以前はRStudioという社名でした)での同僚でもあります。

大きな変更箇所を簡単にまとめると以下のようになります。

-   本書第1部は"全体像"としました。
    第1部の目的は、データサイエンスの詳細に入り込む前に、その"全体像"を大まかに掴んでもらうことです。

-   第2部は"可視化"です。
    第2部では、データを可視化する道具とベストプラクティスを、第1版のときよりも広くカバーしました。
    詳細の全てを得る最良の場所は依然として[ggplot2 book](http://ggplot2-book.org/)ではあるのですが、本書第2版では重要なテクニックをより多くカバーしました。

-   第3部は"変換"と名付けて、数値、論理ベクトル、欠損値についての章を追加。
    第1版ではデータ変換の章で、その一部として扱っていたのですが、詳細の全てをカバーするにはもっと多くのスペースが必要になりました。

-   第4部は"読み込み"です。
    フラットなテキストファイルを読み込むだけでなく、スプレッドシートで仕事をしたり、データベースからデータを取ってきたり、ビッグデータを扱ったり、階層データを矩形化したり、ウェブサイトからデータをスクレイピングする章を追加しました。

-   "プログラム"部は残しましたが、徹底的に書き直して、関数記述と繰り返しの最も重要な部分にフォーカスしました。
    関数記述には、tidyverse関数を包み込む詳細なやり方（tidy evaluationの挑戦の取り扱い方）を含めました。こ
    こ数年に間に、ずっと簡単に、そしてずっと重要になったからです。
    また、ベースR関数で、そこかしこのRコードで見かけそうな重要な関数についての章を追加しました。

-   モデルについての部は削除しました。
    第1版でもモデルを十分に扱えるだけのスペースがありませんでしたが、今ではもっと良い資源が利用可能になっています。
    [tidymodels](https://www.tidymodels.org/) パッケージの使用と、Max KuhnとJulia Silgeによる著作[Tidy Modeling with R](https://www.tmwr.org/)を読むことを一般的に薦めています。

-   "コミュニケート"部は残しましたが、R Markdownに替わって、[Quarto](https://quarto.org/)をメインとするよう、徹底的にアップデートしました。
    この第2版はQuartoで書かれています。Q
    uartoが将来にわたって使われる道具であることは明らかです。
